# Generated by Django 5.1 on 2024-09-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='conquests',
        ),
        migrations.AlterField(
            model_name='stamp',
            name='conquest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='api.conquest'),
        ),
    ]
