# Generated by Django 5.1 on 2024-08-14 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamps_amount', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('painel-palestra-mesa-roda', 'Ppmr'), ('apresentador', 'Presenter'), ('minicurso-desafio_marketing', 'Mini Course Or Marketing'), ('pergunta', 'Question'), ('estande-sipex-integrador-desafio_marketing', 'Presentation'), ('networking-mociteczn', 'Mocitec'), ('voluntario', 'Volunteer')], max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(blank=True, to='api.activity'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('required_conquests', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='awards',
            field=models.ManyToManyField(blank=True, to='api.award'),
        ),
    ]
