# Generated by Django 5.1 on 2024-09-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_award_conquests_alter_stamp_conquest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='event',
        ),
    ]
