# Generated by Django 5.1 on 2024-08-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_user_activities_award_user_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=255)),
                ('required_stamps', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='conquests',
            field=models.ManyToManyField(blank=True, to='api.conquest'),
        ),
    ]
