# Generated by Django 5.1 on 2024-09-27 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_stamp_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 13, 45, 15, 933814)),
            preserve_default=False,
        ),
    ]
