# Generated by Django 5.1 on 2024-08-20 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conquest_award_conquests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('voluntario', 'Volunteer'), ('apresentador', 'Presenter'), ('comum', 'Common')], default='comum', max_length=64),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=128)),
                ('conquest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conquest')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='stamp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.stamp'),
            preserve_default=False,
        ),
    ]
