# Generated by Django 5.1 on 2024-09-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='timestamp',
        ),
    ]
