# Generated by Django 5.1 on 2024-08-23 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='award',
            name='conquests',
        ),
        migrations.RemoveField(
            model_name='award',
            name='event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='conquest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='conquest',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='user_who_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='users_who_participate',
            field=models.ManyToManyField(related_name='events_participating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Conquest',
        ),
        migrations.DeleteModel(
            name='Stamp',
        ),
    ]
